### ISSUE TITLE
Doesn't even start in eclipse 

### ISSUE THREAD

**Issue by Polydiac** [pahimar/LetsModReboot#18]
This is what I get when starting minecraft out of eclipse : 

[21:26:41] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:26:41] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:26:41] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[21:26:41] [main/INFO] [FML]: Forge Mod Loader version 7.10.84.1217 for Minecraft 1.7.10 loading
[21:26:41] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.7.0_60, running on Windows 8.1:x86:6.3, installed at C:\Program Files\Java\jre7
[21:26:41] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[21:26:41] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:26:41] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[21:26:41] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:26:41] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:26:41] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:26:42] [main/ERROR] [FML]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[21:26:44] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[21:26:44] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:26:44] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[21:26:44] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[21:26:44] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[21:26:44] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[21:26:45] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: joptsimple.MissingRequiredOptionException: Missing required option(s) ['userProperties']
    at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:447) ~[OptionParser.class:?]
    at joptsimple.OptionParser.parse(OptionParser.java:437) ~[OptionParser.class:?]
    at net.minecraft.client.main.Main.main(Main.java:89) ~[Main.class:?]
    ... 6 more
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true

 Do I have to provide special arguments?( It works when I start it out of gradle itself)

**Comment by SoulSkin** [comment]
Yes. you need to have "--userProperties " and either "{}" or braces filled with things like twitch.tv steaming info. to just get it to run you need "--userProperties {}" (w/o quotes)

**Comment by pahimar** [comment]
Not a bug with this project - rerun your setup to properly generate the run configurations for your chosen IDE

**Comment by Polydiac** [comment]
Thank you SoulSkin it worked. Sorry Pahimar I didn't know where else to put it.
